[package]
name = "cros_async"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
io_uring = { path = "../io_uring" }
libc = "*"
paste = "*"
pin-utils = "0.1.0-alpha.4"
base = { path = "../base" }
syscall_defines = { path = "../syscall_defines" }

[dependencies.futures]
version = "*"
default-features = false
features = ["alloc"]

[dev-dependencies]
tempfile = { path = "../tempfile" }
vm_memory = { path = "../vm_memory" }
