[package]
name = "vm_control"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
data_model = { path = "../data_model" }
hypervisor = { path = "../hypervisor" }
libc = "*"
msg_socket = { path = "../msg_socket" }
resources = { path = "../resources" }
sync = { path = "../sync" }
base = { path = "../base" }
vm_memory = { path = "../vm_memory" }
