[package]
name = "vm_control"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
data_model = { path = "../data_model" }
kvm = { path = "../kvm" }
libc = "*"
msg_socket = { path = "../msg_socket" }
resources = { path = "../resources" }
sys_util = { path = "../sys_util" }
