[package]
name = "crosvm"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"
default-run = "crosvm"

[lib]
path = "src/crosvm.rs"

[[bin]]
name = "crosvm"
path = "src/main.rs"

[[bin]]
name = "crosvm-direct"
path = "src/main.rs"
required-features = [ "direct" ]

[profile.release]
panic = 'abort'
overflow-checks = true

[workspace]
members = [
    "fuzz",
    "qcow_utils",
    "integration_tests",
    "libcrosvm_control",
]
exclude = [
    "assertions",
    "base",
    "cros_async",
    "data_model",
    "rand_ish",
    "sync",
    "sys_util",
    "tempfile",
    "vm_memory",
]

[features]
default = ["audio", "gpu"]
chromeos = ["base/chromeos"]
default-no-sandbox = []
direct = ["devices/direct"]
audio = ["devices/audio"]
gpu = ["devices/gpu"]
plugin = ["protos/plugin", "crosvm_plugin", "kvm", "kvm_sys", "protobuf"]
power-monitor-powerd = ["arch/power-monitor-powerd"]
tpm = ["devices/tpm"]
video-decoder = ["devices/video-decoder"]
video-encoder = ["devices/video-encoder"]
wl-dmabuf = ["devices/minigbm"]
x = ["devices/x"]
virgl_renderer_next = ["rutabaga_gfx/virgl_renderer_next"]
composite-disk = ["protos/composite-disk", "protobuf", "disk/composite-disk"]
virgl_renderer = ["devices/virgl_renderer"]
gfxstream = ["devices/gfxstream"]
gdb = ["gdbstub", "thiserror",  "arch/gdb", "vm_control/gdb", "x86_64/gdb"]

[dependencies]
arch = { path = "arch" }
assertions = { path = "assertions" }
audio_streams = "*"
base = "*"
bit_field = { path = "bit_field" }
crosvm_plugin = { path = "crosvm_plugin", optional = true }
data_model = "*"
devices = { path = "devices" }
disk = { path = "disk" }
enumn = { path = "enumn" }
gdbstub = { version = "0.4.0", optional = true }
rutabaga_gfx = { path = "rutabaga_gfx"}
hypervisor = { path = "hypervisor" }
kernel_cmdline = { path = "kernel_cmdline" }
kernel_loader = { path = "kernel_loader" }
kvm = { path = "kvm", optional = true }
kvm_sys = { path = "kvm_sys", optional = true }
libc = "0.2.93"
libcras = "*"
minijail = "*" # provided by ebuild
net_util = { path = "net_util" }
p9 = { path = "../vm_tools/p9" }
protobuf = { version = "2.3", optional = true }
protos = { path = "protos", optional = true }
rand_ish = { path = "rand_ish" }
remain = "*"
resources = { path = "resources" }
sync = { path = "sync" }
tempfile = "*"
thiserror = { version = "1.0.20", optional = true }
vhost = { path = "vhost" }
vm_control = { path = "vm_control" }
acpi_tables = { path = "acpi_tables" }
vm_memory = { path = "vm_memory" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = { path = "x86_64" }

[target.'cfg(any(target_arch = "aarch64", target_arch = "arm"))'.dependencies]
aarch64 = { path = "aarch64" }

[dev-dependencies]
base = "*"

[patch.crates-io]
assertions = { path = "assertions" }
audio_streams = { path = "../adhd/audio_streams" } # ignored by ebuild
base = { path = "base" }
cros_fuzz = { path = "../../platform2/cros-fuzz" } # ignored by ebuild
data_model = { path = "data_model" }
libchromeos = { path = "../libchromeos-rs" } # ignored by ebuild
libcras = { path = "../adhd/cras/client/libcras" } # ignored by ebuild
minijail = { path = "../minijail/rust/minijail" } # ignored by ebuild
p9 = { path = "../vm_tools/p9" } # ignored by ebuild
sync = { path = "sync" }
sys_util = { path = "sys_util" }
tempfile = { path = "tempfile" }
wire_format_derive = { path = "../vm_tools/p9/wire_format_derive" } # ignored by ebuild
vmm_vhost = { path = "../rust/crates/vhost", features = ["vhost-user-master"] } # ignored by ebuild
