[package]
name = "net_util"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
libc = "*"
data_model = { path = "../data_model" }
net_sys = { path = "../net_sys" }
sys_util = { path = "../sys_util" }
