[package]
name = "gpu_display"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[features]
x = []

[dependencies]
data_model = { path = "../data_model" }
libc = "*"
sys_util = { path = "../sys_util" }
linux_input_sys = { path = "../linux_input_sys" }

[build-dependencies]
cc = "=1.0.25"
