[package]
name = "kernel_loader"
version = "0.1.0"
edition = "2018"

[dependencies]
data_model = { path = "../common/data_model" }
libc = "*"
base = { path = "../common/base" }
remain = "*"
thiserror = "*"
vm_memory = { path = "../vm_memory" }

[dev-dependencies]
tempfile = "3"
