[package]
name = "x86_64"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[features]
gdb = ["gdbstub", "msg_socket", "arch/gdb"]

[dependencies]
arch = { path = "../arch" }
assertions = { path = "../assertions" }
data_model = { path = "../data_model" }
devices = { path = "../devices" }
gdbstub = { version = "0.4.0", optional = true }
hypervisor = { path = "../hypervisor" }
kernel_cmdline = { path = "../kernel_cmdline" }
kernel_loader = { path = "../kernel_loader" }
libc = "*"
minijail = { path = "../../minijail/rust/minijail" } # ignored by ebuild
msg_socket = { path = "../msg_socket", optional = true }
remain = "*"
resources = { path = "../resources" }
sync = { path = "../sync" }
base = { path = "../base" }
acpi_tables = {path = "../acpi_tables" }
vm_control = { path = "../vm_control" }
vm_memory = { path = "../vm_memory" }

[dev-dependencies]
msg_socket = { path = "../msg_socket"}