[package]
name = "devices"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[features]
audio = []
gpu = ["gpu_buffer", "gpu_display", "gpu_renderer"]
tpm = ["protos/trunks", "tpm2"]
video-decoder = []
video-encoder = []
wl-dmabuf = []
x = ["gpu_display/x"]
gfxstream = ["gpu", "gpu_renderer/gfxstream"]

[dependencies]
acpi_tables = {path = "../acpi_tables" }
audio_streams = { path = "../../adhd/audio_streams" } # ignored by ebuild
bit_field = { path = "../bit_field" }
bitflags = "1"
cros_async = { path = "../cros_async" }
data_model = { path = "../data_model" }
disk = { path = "../disk" }
enumn = { path = "../enumn" }
gpu_buffer = { path = "../gpu_buffer", optional = true }
gpu_display = { path = "../gpu_display", optional = true }
gpu_renderer = { path = "../gpu_renderer", optional = true }
hypervisor = { path = "../hypervisor" }
kvm_sys = { path = "../kvm_sys" }
libc = "*"
libcras = { path = "../../adhd/cras/client/libcras" } # ignored by ebuild
linux_input_sys = { path = "../linux_input_sys" }
minijail = { path = "../../minijail/rust/minijail" } # ignored by ebuild
msg_on_socket_derive = { path = "../msg_socket/msg_on_socket_derive" }
msg_socket = { path = "../msg_socket" }
net_sys = { path = "../net_sys" }
net_util = { path = "../net_util" }
p9 = { path = "../../vm_tools/p9" }
protos = { path = "../protos", optional = true }
rand_ish = { path = "../rand_ish" }
remain = "*"
resources = { path = "../resources" }
sync = { path = "../sync" }
base = { path = "../base" }
syscall_defines = { path = "../syscall_defines" }
tpm2 = { path = "../tpm2", optional = true }
usb_util = { path = "../usb_util" }
vfio_sys = { path = "../vfio_sys" }
vhost = { path = "../vhost" }
virtio_sys = { path = "../virtio_sys" }
vm_control = { path = "../vm_control" }
vm_memory = { path = "../vm_memory" }

[dev-dependencies]
tempfile = { path = "../tempfile" }
