# Disable clippy lints project-wide.
# This allows ./tools/clippy and IDE integrations to use the same configuration.
# This should be replaced with a proper clippy config once available:
# https://github.com/rust-lang/cargo/issues/5034
[target.'cfg(all())']
rustflags = [
    # TODO(b/181763000): Fail builds on warnings
    # "-Dwarnings",

    # TODO(crbug/908640): To be resolved.
    "-Aclippy::needless_return",
    "-Aclippy::needless_doctest_main",
    "-Aclippy::blocks_in_if_conditions",
    "-Aclippy::missing_safety_doc", # 26 errors

    # False positives affecting WlVfd @ `devices/src/virtio/wl.rs`.
    # Bug: https://github.com/rust-lang/rust-clippy/issues/6312
    "-Aclippy::field_reassign_with_default",

    # We don't care about these lints. Okay to remain suppressed globally.
    "-Aclippy::cast_lossless",
    "-Aclippy::cognitive_complexity",
    "-Aclippy::enum_variant_names",
    "-Aclippy::identity_op",
    "-Aclippy::len_without_is_empty",
    "-Aclippy::len_zero",
    "-Aclippy::match_bool",
    "-Aclippy::match_wild_err_arm",
    "-Aclippy::module_inception",
    "-Aclippy::needless_bool",
    "-Aclippy::new_without_default",
    "-Aclippy::or_fun_call",
    "-Aclippy::should_implement_trait",
    "-Aclippy::single_char_pattern",
    "-Aclippy::too_many_arguments",
    "-Aclippy::trivially_copy_pass_by_ref",
    "-Aclippy::type_complexity",
    "-Aclippy::unreadable_literal",
    "-Aclippy::useless_let_if_seq",
    "-Aclippy::useless_transmute",
    "-Aclippy::new-ret-no-self",
    "-Aclippy::result-unit-err",
    "-Aclippy::collapsible_if",
]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
