[package]
name = "qcow_utils"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[lib]
path = "src/qcow_utils.rs"
crate-type = ["cdylib"]

[dependencies]
libc = "*"
disk = { path = "../disk" }
base = { path = "../common/base" }
