[package]
name = "disk"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[lib]
path = "src/disk.rs"

[dependencies]
libc = "*"
remain = "*"
qcow = { path = "../qcow" }
sys_util = { path = "../sys_util" }
