[package]
name = "usb_util"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
assertions = { path = "../assertions" }
data_model = { path = "../data_model" }
libc = "*"
remain = "*"
sys_util = { path = "../sys_util" }
usb_sys = { path = "../usb_sys" }
