# Autogenerated via gen_android.sh
#
# Copyright (C) 2020 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

crosvm_inline_seccomp_policy_x86_64 := \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/9p_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/balloon_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/block_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/cras_audio_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/fs_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/gpu_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/input_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/net_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/null_audio_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/pmem_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/rng_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/serial.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/tpm_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/vfio_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/vhost_net_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/vhost_vsock_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/video_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/wl_device.policy \
    usr/share/crosvm/x86_64-linux-gnu/seccomp/xhci.policy \

crosvm_inline_seccomp_policy_aarch64 := \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/9p_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/balloon_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/block_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/cras_audio_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/fs_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/gpu_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/input_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/net_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/null_audio_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/pmem_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/rng_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/serial.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/tpm_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/vhost_net_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/vhost_vsock_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/wl_device.policy \
    usr/share/crosvm/aarch64-linux-gnu/seccomp/xhci.policy \

