[package]
name = "sys_util_core"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]

[dependencies]
libc = "*"
remain = "0.2"
thiserror = "*"

[workspace]
