[package]
name = "msg_on_socket_derive"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
base = "*"
proc-macro2 = "^1"
quote = "^1"
syn = "^1"

[lib]
proc-macro = true
path = "msg_on_socket_derive.rs"
