[package]
name = "fuse"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
base = { path = "../common/base" }
bitflags = "1"
data_model = { path = "../common/data_model" }
enumn = "0.1.0"
libc = "*"
remain = "0.2"
thiserror = "1.0.20"
