[package]
name = "vm_memory"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]

[dependencies]
cros_async = { path = "../common/cros_async" }
data_model = { path = "../common/data_model" }
libc = "*"
base = { path = "../common/base" }
bitflags = "1"
remain = "*"
serde = { version = "1", features = [ "derive" ] }
thiserror = "*"


